# Generated by Django 5.0.3 on 2024-05-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pendaftaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('tanggal_lahir', models.CharField(max_length=255)),
                ('jenis_kelamin', models.CharField(max_length=255)),
                ('alamat', models.CharField(max_length=255)),
                ('nomor_telepon', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sekolah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sekolah', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('tanggal_lahir', models.CharField(max_length=255)),
                ('alamat', models.CharField(max_length=255)),
                ('nomor_telepon', models.CharField(max_length=255)),
                ('nilai_ujian', models.CharField(max_length=255)),
            ],
        ),
    ]
