# Generated by Django 5.0.3 on 2024-05-05 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sekolah',
            old_name='nama_sekolah',
            new_name='nama',
        ),
    ]
